name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      zip: ${{ steps.zip.outputs.zip-path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe
        run: pyinstaller --onefile --name AutoExcelToDoc AutoExcelToDoc.py

      - name: Zip .exe
        id: zip
        run: |
          powershell Compress-Archive -Path dist\AutoExcelToDoc.exe -DestinationPath AutoExcelToDoc-Windows.zip
          echo "zip-path=AutoExcelToDoc-Windows.zip" >> $env:GITHUB_OUTPUT

  build-macos:
    runs-on: macos-latest
    outputs:
      zip: ${{ steps.zip.outputs.zip-path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build mac binary
        run: pyinstaller --onefile --name AutoExcelToDoc AutoExcelToDoc.py

      - name: Zip mac binary
        id: zip
        run: |
          zip -j AutoExcelToDoc-macOS.zip dist/AutoExcelToDoc
          echo "zip-path=AutoExcelToDoc-macOS.zip" >> $GITHUB_OUTPUT

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AutoExcelToDoc-Windows.zip
            AutoExcelToDoc-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
